# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buy', '0002_auto_20160329_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyDiamond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diamond_total_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DiamondTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('diamond_num', models.IntegerField(default=0)),
                ('trade_date', models.DateTimeField(verbose_name='trade date')),
            ],
        ),
    ]
